### ISSUE TITLE
[Bugs] 关于移植到ArchLinux后几个问题的反馈

### ISSUE THREAD

**Issue by zxp19821005** [027xiguapi/pear-rec#75]
如题。我已经将其移植到了Archlinux的AUR：https://aur.archlinux.org/packages/pear-rec ，在移植和运行中发现了几个问题：
### 缺少Linux图标文件
编译时，提示
```
⨯ icon directory /home/zxp-endeavouros/.cache/paru/clone/pear-rec/src/pear-rec-1.3.2/packages/desktop/build/icons doesn't contain icons
github.com/develar/app-builder/pkg/icons.CollectIcons
        /Volumes/data/Documents/app-builder/pkg/icons/collect-icons.go:73
github.com/develar/app-builder/pkg/icons.doConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:191
github.com/develar/app-builder/pkg/icons.ConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:255
runtime.goexit
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581
github.com/develar/app-builder/pkg/icons.doConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:193
github.com/develar/app-builder/pkg/icons.ConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:255
runtime.goexit
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581  
  ⨯ /home/zxp-endeavouros/.cache/paru/clone/pear-rec/src/pear-rec-1.3.2/node_modules/.pnpm/app-builder-bin@4.0.0/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: /home/zxp-endeavouros/.cache/paru/clone/pear-rec/src/pear-rec-1.3.2/node_modules/.pnpm/app-builder-bin@4.0.0/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```
这个我在移植的时候添加了一行代码自行解决了：
```
sed "20i\    icon: 'build/icons/png/1024x1024.png'," -i packages/desktop/electron-builder.json5
```
### favicon.ico问题
打包完成后运行，提示：
```
$ pear-rec
[266742:1206/153549.344944:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[266742:1206/153549.344982:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
(node:266742) UnhandledPromiseRejectionWarning: Error: Failed to load image from path '/usr/lib/pear-rec/app/dist/imgs/logo/favicon.ico'
```
这个我自行解决了：
```
sed "s|favicon.ico|favicon.png|g" -i "packages/desktop/release/${pkgver}/linux-unpacked/resources/app/dist-electron/main/index.js"
cp packages/desktop/build/icons/png/32x32.png "packages/desktop/release/${pkgver}/linux-unpacked/resources/app/dist/imgs/logo/favicon.png"
```
但是这个是在编译完成后替换已编译文件中的内容，前面我尝试直接修改源代码中的对应文件，不知道怎么回事，不生效。我本人也不会编程，所以得麻烦您再看一下。

### 日志文件问题
程序运行后，有一个报错：
```
TypeORM connection error:  Error: EACCES: permission denied, open '/usr/lib/pear-rec/app/ormlogs.log'
```
不知道这个日志文件能不能放到 `$HOME/.config/pear-rec`目录中？
虽然好像不影响使用
我个人目前解决如下：
```
sudo touch /usr/lib/pear-rec/app/ormlogs.log
sudo chmod 666 /usr/lib/pear-rec/app/
```

#### 截屏目前不可用
运行后提示
```Error occurred in handler for 'ss:get-shot-screen-img': TypeError: Cannot read properties of undefined (reading 'thumbnail')
    at /usr/lib/pear-rec/app/dist-electron/main/index.js:5:2090
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89579)
```
#### 录屏目前不可用
运行后提示：
![image](https://github.com/027xiguapi/pear-rec/assets/4915850/d1ac8de8-6a74-4ca8-80b5-9e998d97fdd5)
#### 录像功能正常
可以调用我笔记本电脑的摄像头录像
#### 查看功能正常
可以查看图片、视频，音频未测试

**Comment by zxp19821005** [comment]
那不知道具体的编译打包步骤有么？Win版的也可以参考一下。
不知道是不是这样的：
```
pnpm install
pnpm run build:web
pnpm run build:server
pnpm run build:screenshot
pnpm run build:recorder
pnpm run build:timer
pnpm run build:desktop
```

**Comment by zxp19821005** [comment]
[1.3.8]版本在AR出Linux中编译失败
nodejs版本: 16 和 21 都测试过了
报错信息：
```
> @pear-rec/web@1.3.10 build /home/zxp-endeavouros/.cache/paru/clone/pear-rec/src/pear-rec/packages/web
> rimraf dist && tsc && vite build

src/components/upload/UploadImg.tsx:20:23 - error TS1109: Expression expected.

20     <Space className={...className} style={...style}>
                         ~~~

src/components/upload/UploadImg.tsx:20:35 - error TS1003: Identifier expected.

20     <Space className={...className} style={...style}>
                                     ~

src/components/upload/UploadImg.tsx:21:7 - error TS2657: JSX expressions must have one parent element.

 21       <Button type="primary" onClick={handleUpload}>
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 22       {children || '图片'}
    ~~~~~~~~~~~~~~~~~~~~~~~~
... 
 29         onChange={handleUploadImg}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 30       />
    ~~~~~~~~

src/components/upload/UploadImg.tsx:31:5 - error TS1128: Declaration or statement expected.

31     </Space>
       ~~

src/components/upload/UploadImg.tsx:32:3 - error TS1109: Expression expected.

32   );
     ~

src/components/upload/UploadImg.tsx:33:1 - error TS1128: Declaration or statement expected.

33 }
   ~


Found 6 errors in the same file, starting at: src/components/upload/UploadImg.tsx:20

 ELIFECYCLE  Command failed with exit code 2.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
==> 错误： 在 build() 中发生一个错误。
    正在放弃...
```

**Comment by 027xiguapi** [comment]
#91 在这个提交已经修改了这个bug，可以更新代码

**Comment by zxp19821005** [comment]
谢谢！
但是目前还有新的问题：
按照ArchLinux打包nodejs准则，我使用系统自带的electron26运行报错：
```
$ env ELECTRON_IS_DEV=0 NODE_ENV=production electron26 app.asar                 
(node:288968) UnhandledPromiseRejectionWarning: Error: Failed to load image from path '/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/pear-rec/packages/desktop/release/linux-unpacked/resources/app.asar/dist/imgs/logo/favicon.ico'
    at ki (/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/pear-rec/packages/desktop/release/linux-unpacked/resources/app.asar/dist-electron/main/index.js:1:15526)
    at /home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/pear-rec/packages/desktop/release/linux-unpacked/resources/app.asar/dist-electron/main/index.js:12:29565
(Use `electron26 --trace-warnings ...` to show where the warning was created)
(node:288968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[288968:1229/151933.620476:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.freedesktop.portal.Settings 的对象上没有“/org/freedesktop/portal/desktop”接口
serverProcess err: node:internal/modules/cjs/loader:1087
  throw err;
  ^

Error: Cannot find module './globals'
Require stack:
- /home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/pear-rec/packages/desktop/release/linux-unpacked/resources/app.asar/dist-electron/server/main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/utility_init:2:3040)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/pear-rec/packages/desktop/release/linux-unpacked/resources/app.asar/dist-electron/server/main.js:62067:22)
    at __webpack_require__ (/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/pear-rec/packages/desktop/release/linux-unpacked/resources/app.asar/dist-electron/server/main.js:75504:42)
    at Object.defineProperty.value (/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/pear-rec/packages/desktop/release/linux-unpacked/resources/app.asar/dist-electron/server/main.js:61931:19)
    at __webpack_require__ (/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/pear-rec/packages/desktop/release/linux-unpacked/resources/app.asar/dist-electron/server/main.js:75504:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/pear-rec/packages/desktop/release/linux-unpacked/resources/app.asar/dist-electron/server/main.js',
    undefined
  ]
}

Node.js v18.16.1
```
其中`favicon.ico`的问题我前面已经反馈过，但是似乎依然没有修复；
而运行时报错的这个：
```
Error: Cannot find module './globals'
```
我在编译时添加了
```
pnpm add -w globals
```
错误依旧。
能不能麻烦你再看一下？

**Comment by zxp19821005** [comment]
```
# Maintainer: zxp19821005 <zxp19821005 at 163 dot com>
pkgname=pear-rec-git
pkgver=1.3.8.r1.ga0486a2
_electronversion=26
pkgrel=1
pkgdesc="An open-source, cross-platform terminal for seamless workflows"
arch=(
    'x86_64'
)
url="https://027xiguapi.github.io/pear-rec/"
_ghurl="https://github.com/027xiguapi/pear-rec"
license=('Apache')
conflicts=("${pkgname%-git}")
provides=("${pkgname%-git}")
depends=(
    "electron${_electronversion}"
)
makedepends=(
    'gendesk'
    'npm'
    'nodejs>=20'
    'git'
    'pnpm'
    'make'
    'gcc'
    'asar'
)
source=(
    "${pkgname%-git}::git+${_ghurl}.git"
    "${pkgname%-git}.sh"
)
sha256sums=('SKIP'
            'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855')
pkgver() {
    cd "${srcdir}/${pkgname%-git}"
    git describe --long --tags --exclude='*[a-z][a-z]*' | sed -E 's/^v//;s/([^-]*-g)/r\1/;s/-/./g'
}
build() {
    sed -e "s|@electronversion@|${_electronversion}|" \
        -e "s|@appname@|${pkgname%-git}|g" \
        -e "s|@appasar@|app|g" \
        -i "${srcdir}/${pkgname%-git}.sh"
    gendesk -f -n -q --categories "Utility" --exec "${pkgname%-git}"
    cd "${srcdir}/${pkgname%-git}"
    export npm_config_build_from_source=true
    export ELECTRON_SKIP_BINARY_DOWNLOAD=1
    export SYSTEM_ELECTRON_VERSION="$(electron${_electronversion} -v | sed 's/v//g')"
    export ELECTRONVERSION="${_electronversion}"
    sed "s|release/\${version}|release|g" -i packages/desktop/electron-builder.json5
    sed "s|React, ||g" -i packages/timer/src/useTimer.tsx
    pnpm config set store-dir "${srcdir}/.pnpm_store"
    pnpm config set cache-dir "${srcdir}/.pnpm_cache"
    pnpm config set link-workspace-packages true
    pnpm install
    pnpm add -w globals tslib
    pnpm run build:screenshot
    pnpm run build:recorder
    pnpm run build:timer
    pnpm run build:docs
    pnpm run build:desktop
    asar e packages/desktop/release/linux-unpacked/resources/app.asar "${srcdir}/app.asar.unpacked"
    sed "s|favicon.ico|favicon.png|g" -i "${srcdir}/app.asar.unpacked/dist-electron/main/index.js"
    cp "${srcdir}/app.asar.unpacked/dist/imgs/logo/logo.png" "${srcdir}/app.asar.unpacked/dist/imgs/logo/favicon.png"
    asar p "${srcdir}/app.asar.unpacked" "${srcdir}/app.asar"
}
package() {
    install -Dm755 "${srcdir}/${pkgname%-git}.sh" "${pkgdir}/usr/bin/${pkgname%-git}"
    install -Dm755 -d "${pkgdir}/usr/lib/${pkgname%-git}"
    cp -r "${srcdir}/${pkgname%-git}/packages/desktop/release/${pkgver}/linux-unpacked/resources/app" "${pkgdir}/usr/lib/${pkgname%-git}"
    install -Dm644 "${srcdir}/${pkgname%-git}.desktop" -t "${pkgdir}/usr/share/applications"
    for _icons in 16x16 24x24 32x32 48x48 64x64 128x128 256x256 512x512 1024x1024;do
        install -Dm644 "${srcdir}/${pkgname%-git}/packages/desktop/build/icons/png/${_icons}.png" \
            "${pkgdir}/usr/share/icons/hicolor/${_icons}/apps/${pkgname%-git}.png"
    done
}
```
```
#!/bin/sh
set -e
_APPDIR="/usr/lib/@appname@"
_ASAR="${_APPDIR}/@appasar@"
export PATH="${_APPDIR}:${PATH}"
export LD_LIBRARY_PATH="${_APPDIR}/swiftshader:${_APPDIR}/lib:${LD_LIBRARY_PATH}"
export ELECTRON_IS_DEV=0
export NODE_ENV=production
if [[ $EUID -ne 0 ]] || [[ $ELECTRON_RUN_AS_NODE ]]; then
    cd "${_APPDIR}"
    exec electron@electronversion@ "${_ASAR}" "$@"
    exit
else
    cd "${_APPDIR}"
    exec electron@electronversion@ "${_ASAR}" --no-sandbox "$@"
    exit
fi
```
这个是完整的编译打包脚本，刚才编译成功后又出来新的问题
```
$ env ELECTRON_IS_DEV=0 NODE_ENV=production electron26 app.asar 
[308566:1229/154545.495769:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.freedesktop.portal.Settings 的对象上没有“/org/freedesktop/portal/desktop”接口
serverProcess err: node:internal/modules/cjs/loader:1087
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- /home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/app.asar/dist-electron/server/main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/utility_init:2:3040)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/app.asar/dist-electron/server/main.js:62060:17)
    at __webpack_require__ (/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/app.asar/dist-electron/server/main.js:75504:42)
    at Object.defineProperty.value (/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/app.asar/dist-electron/server/main.js:61931:19)
    at __webpack_require__ (/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/app.asar/dist-electron/server/main.js:75504:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/app.asar/dist-electron/server/main.js',
    undefined
  ]
}

Node.js v18.16.1

Error occurred in handler for 'ss:get-shot-screen-img': TypeError: Cannot read properties of undefined (reading 'thumbnail')
    at /home/zxp-endeavouros/.cache/paru/clone/pear-rec-git/src/app.asar/dist-electron/main/index.js:12:26418
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89579)
```
